name: Generate Trophies

on:
  # schedule:
    # - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/trophies.yml'

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Profile Trophy Action
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: 'username=${{ github.repository_owner }}&margin-h=18&margin-w=66&no-bg=true&theme=dark_lover&column=3'
          path: github-trophies.svg
          token: ${{ secrets.HOME }}

      - name: Commit trophy card
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-trophies.svg
          git commit -m "Update README trophy" || exit 0
          git push
